"""Compatibility shim for the canonical technical indicators API.

The implementation is authoritative in researchos.quant_engine.technical.indicators.
"""

from researchos.quant_engine.technical.indicators import (
    accumulation_distribution,
    adx,
    atr,
    bollinger_bands,
    cci,
    cmf,
    dmi,
    donchian_channel,
    ema,
    hma,
    ichimoku_cloud,
    keltner_channel,
    macd,
    mfi,
    momentum,
    obv,
    parabolic_sar,
    roc,
    rsi,
    sma,
    stochastic,
    supertrend,
    vwap,
    vwma,
    wma,
)

__all__ = [
    "sma",
    "ema",
    "wma",
    "hma",
    "vwma",
    "rsi",
    "stochastic",
    "cci",
    "roc",
    "momentum",
    "atr",
    "bollinger_bands",
    "keltner_channel",
    "donchian_channel",
    "obv",
    "vwap",
    "mfi",
    "cmf",
    "accumulation_distribution",
    "dmi",
    "adx",
    "macd",
    "supertrend",
    "ichimoku_cloud",
    "parabolic_sar",
]
